protocols = imap lmtp sieve
listen = *

mail_location = maildir:/home/mailservers/%d/%n/Maildir
mail_uid = 5000
mail_gid = 5000
first_valid_uid = 5000
last_valid_uid = 5000

mail_plugins = $mail_plugins quota

auth_mechanisms = plain login

ssl = required
ssl_cert = </certs/default/fullchain.pem
ssl_key = </certs/default/privkey.pem

haproxy_trusted_networks = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

namespace inbox {
  inbox = yes
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
}

protocol imap {
  mail_plugins = $mail_plugins imap_quota
}

protocol lmtp {
  mail_plugins = $mail_plugins sieve
}

plugin {
  quota = maildir:User quota
  sieve = /var/sieve/%d/%n.sieve
}

service auth {
  inet_listener {
    port = 12345
  }
}

service lmtp {
  inet_listener lmtp {
    port = 24
  }
}

service imap-login {
  inet_listener imap {
    port = 2143
    haproxy = yes
  }
  inet_listener imaps {
    port = 2993
    ssl = no
    haproxy = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 0
  }
  inet_listener pop3s {
    port = 0
  }
}

!include_try /gen-config/dovecot/sni.conf
