Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes
UMask                   002

Canonicalization        relaxed/simple
Mode                    sv
SubDomains              no
OversignHeaders         From

KeyTable                refile:/gen-config/opendkim/key.table
SigningTable            refile:/gen-config/opendkim/signing.table
ExternalIgnoreList      refile:/gen-config/opendkim/trusted.hosts
InternalHosts           refile:/gen-config/opendkim/trusted.hosts

Socket                  inet:8891@0.0.0.0

PidFile                 /var/run/opendkim/opendkim.pid
TemporaryDirectory      /var/tmp
